version: '3'
services:
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./volumes/ngxproxy/data:/data
      - ./volumes/letsencrypt:/etc/letsencrypt

  db:
    image: postgres:alpine
    restart: unless-stopped
    container_name: postgre_lib
    ports:
      - '5432:5432'
    env_file: ./backend/.env
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
      - ./volumes/postgres/initial_sql/initial_db.sql:/docker-entrypoint-initdb.d/create_schemas.sql
    depends_on:
      - proxy
    networks:
      -  postgre-network

  api:
    build:
      context: ./backend
      dockerfile: ./docker/swoole/Dockerfile
    container_name: backend_lib
    restart: unless-stopped
    volumes:
      -  ./backend:/var/www
      -  ./backend/docker/swoole/extend-php.ini:/usr/local/etc/php/conf.d/extend-php.ini
    ports:
      - "8000:80"
    depends_on:
      - proxy
      - app
    networks:
      -  postgre-network
      -  api-network

  web:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: frontend_lib
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - api
      - proxy
    networks:
      -  api-network

networks:
  postgre-network:
  api-network:
